apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-h77z
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0042-tenant/tkrw-pr712-0075-0042-app/devfile-sample-h77z@sha256:9be1568ac695f90a2a879f2eca3064e7683a179111b5c49a0ea63dd8134d713f
        name: my-nodejs
        resources: {}
status: {}
